services:
  - type: web
    name: boilerplate-infosec
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
